#!/bin/bash
_generated_func_() {
    local curlRetCode="$1"
    local msg
    case "$curlRetCode" in
       0) echo "Success. The operation completed successfully according to the instructions." ;;
       1) echo "Unsupported protocol. This build of curl has no support for this protocol." ;;
       2) echo "Failed to initialize." ;;
       3) echo "URL malformed. The syntax was not correct." ;;
       4) echo "A feature or option that was needed to perform the desired request was not enabled or was explicitly disabled at build-time. To make curl able to do this, you probably need another build of libcurl." ;;
       5) echo "Could not resolve proxy. The given proxy host could not be resolved." ;;
       6) echo "Could not resolve host. The given remote host could not be resolved." ;;
       7) echo "Failed to connect to host." ;;
       8) echo "Weird server reply. The server sent data curl could not parse." ;;
       9) echo "FTP access denied. The server denied login or denied access to the particular resource or directory you wanted to reach. Most often you tried to change to a directory that does not exist on the server." ;;
       10) echo "FTP accept failed. While waiting for the server to connect back when an active FTP session is used, an error code was sent over the control connection or similar." ;;
       11) echo "FTP weird PASS reply. Curl could not parse the reply sent to the PASS request." ;;
       12) echo "During an active FTP session while waiting for the server to connect back to curl, the timeout expired." ;;
       13) echo "FTP weird PASV reply, Curl could not parse the reply sent to the PASV request." ;;
       14) echo "FTP weird 227 format. Curl could not parse the 227-line the server sent." ;;
       15) echo "FTP cannot use host. Could not resolve the host IP we got in the 227-line." ;;
       16) echo "HTTP/2 error. A problem was detected in the HTTP2 framing layer. This is somewhat generic and can be one out of several problems, see the error message for details." ;;
       17) echo "FTP could not set binary. Could not change transfer method to binary." ;;
       18) echo "Partial file. Only a part of the file was transferred." ;;
       19) echo "FTP could not download/access the given file, the RETR (or similar) command failed." ;;
       21) echo "FTP quote error. A quote command returned error from the server." ;;
       22) echo "HTTP page not retrieved. The requested URL was not found or returned another error with the HTTP error code being 400 or above. This return code only appears if --fail is used." ;;
       23) echo "Write error. Curl could not write data to a local filesystem or similar." ;;
       25) echo "FTP could not STOR file. The server denied the STOR operation, used for FTP uploading." ;;
       26) echo "Read error. Various reading problems." ;;
       27) echo "Out of memory. A memory allocation request failed." ;;
       28) echo "Operation timeout. The specified time-out period was reached according to the conditions." ;;
       30) echo "FTP PORT failed. The PORT command failed. Not all FTP servers support the PORT command, try doing a transfer using PASV instead!" ;;
       31) echo "FTP could not use REST. The REST command failed. This command is used for resumed FTP transfers." ;;
       33) echo "HTTP range error. The range 'command' did not work." ;;
       34) echo "HTTP post error. Internal post-request generation error." ;;
       35) echo "SSL connect error. The SSL handshaking failed." ;;
       36) echo "Bad download resume. Could not continue an earlier aborted download." ;;
       37) echo "FILE could not read file. Failed to open the file. Permissions?" ;;
       38) echo "LDAP cannot bind. LDAP bind operation failed." ;;
       39) echo "LDAP search failed." ;;
       41) echo "Function not found. A required LDAP function was not found." ;;
       42) echo "Aborted by callback. An application told curl to abort the operation." ;;
       43) echo "Internal error. A function was called with a bad parameter." ;;
       45) echo "Interface error. A specified outgoing interface could not be used." ;;
       47) echo "Too many redirects. When following redirects, curl hit the maximum amount." ;;
       48) echo "Unknown option specified to libcurl. This indicates that you passed a weird option to curl that was passed on to libcurl and rejected. Read up in the manual!" ;;
       49) echo "Malformed telnet option." ;;
       52) echo "The server did not reply anything, which here is considered an error." ;;
       53) echo "SSL crypto engine not found." ;;
       54) echo "Cannot set SSL crypto engine as default." ;;
       55) echo "Failed sending network data." ;;
       56) echo "Failure in receiving network data." ;;
       58) echo "Problem with the local certificate." ;;
       59) echo "Could not use specified SSL cipher." ;;
       60) echo "Peer certificate cannot be authenticated with known CA certificates." ;;
       61) echo "Unrecognized transfer encoding." ;;
       63) echo "Maximum file size exceeded." ;;
       64) echo "Requested FTP SSL level failed." ;;
       65) echo "Sending the data requires a rewind that failed." ;;
       66) echo "Failed to initialise SSL Engine." ;;
       67) echo "The user name, password, or similar was not accepted and curl failed to log in." ;;
       68) echo "File not found on TFTP server." ;;
       69) echo "Permission problem on TFTP server." ;;
       70) echo "Out of disk space on TFTP server." ;;
       71) echo "Illegal TFTP operation." ;;
       72) echo "Unknown TFTP transfer ID." ;;
       73) echo "File already exists (TFTP)." ;;
       74) echo "No such user (TFTP)." ;;
       77) echo "Problem reading the SSL CA cert (path? access rights?)." ;;
       78) echo "The resource referenced in the URL does not exist." ;;
       79) echo "An unspecified error occurred during the SSH session." ;;
       80) echo "Failed to shut down the SSL connection." ;;
       82) echo "Could not load CRL file, missing or wrong format." ;;
       83) echo "Issuer check failed." ;;
       84) echo "The FTP PRET command failed." ;;
       85) echo "Mismatch of RTSP CSeq numbers." ;;
       86) echo "Mismatch of RTSP Session Identifiers." ;;
       87) echo "Unable to parse FTP file list." ;;
       88) echo "FTP chunk callback reported error." ;;
       89) echo "No connection available, the session will be queued." ;;
       90) echo "SSL public key does not matched pinned public key." ;;
       91) echo "Invalid SSL certificate status." ;;
       92) echo "Stream error in HTTP/2 framing layer." ;;
       93) echo "An API function was called from inside a callback." ;;
       94) echo "An authentication function returned an error." ;;
       95) echo "A problem was detected in the HTTP/3 layer. This is somewhat generic and can be one out of several problems, see the error message for details." ;;
       96) echo "QUIC connection error. This error may be caused by an SSL library error. QUIC is the protocol used for HTTP/3 transfers." ;;
       0) echo "OK" ;;
       *) echo "[Error] The manual page of 'curl' does not recognize error code '$curlRetCode'."
          return 1
          ;;
    esac
}
_generated_func_ "$1"
